### ISSUE TITLE
Proposal logo design

### ISSUE THREAD

**Issue by jbeguna04** [andreyrd/ListLauncher#38]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. This issue is not saying that your current logo is unsatisfactory, I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by andreyrd** [comment]
Hello! I agree that the logo needs to be updated.
Someone did actually already send me a new logo several days ago that I plan on using soon as I find the time to change to it!

**Comment by jbeguna04** [comment]
Thank you for the reply. More power to your app
